name: Greetings

on: 
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Greet first-time contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "🎉 Thanks for opening your first issue! We appreciate your contribution. A maintainer will review it soon."
          pr-message: "🚀 Thanks for submitting your first pull request! Your contribution is valuable. A reviewer will check it out soon."
run-name: Arlett
